import type { Template } from "@/templates/types";
import { Layout } from "./Layout";

export const fumadocs: Template = {
  id: "fumadocs",
  displayName: "Fumadocs",
  description:
    "Docs-first marketing landing. Pill badge, big headline with brand-color accent, primary + secondary CTAs, and a rounded-card feature grid.",
  sourceUrl: "https://github.com/fuma-nama/fumadocs",
  sourceAttribution: "template sourced from vercel · fumadocs",
  license: "MIT",
  tags: ["docs", "marketing", "framework", "dark", "rounded"],
  Layout,
  copySchema: [
    {
      key: "hero.badge",
      label: "Pill badge text",
      type: "text",
      placeholder: "the docs framework you love.",
      required: true,
      maxLength: 80,
    },
    {
      key: "hero.headlinePart1",
      label: "Headline — start",
      type: "text",
      placeholder: "Build excellent",
      required: true,
      maxLength: 60,
    },
    {
      key: "hero.headlineAccent",
      label: "Headline — accent word",
      type: "text",
      placeholder: "documentations",
      required: true,
      maxLength: 30,
    },
    {
      key: "hero.headlinePart2",
      label: "Headline — trailing phrase (optional)",
      type: "text",
      placeholder: "your way.",
      required: false,
      maxLength: 60,
    },
    {
      key: "hero.primaryCtaLabel",
      label: "Primary CTA label",
      type: "text",
      placeholder: "Get started",
      required: true,
      maxLength: 24,
    },
    {
      key: "hero.primaryCtaHref",
      label: "Primary CTA link",
      type: "text",
      placeholder: "https://example.com/start",
      required: true,
    },
    {
      key: "hero.secondaryCtaLabel",
      label: "Secondary CTA label (optional)",
      type: "text",
      placeholder: "View on CodeSandbox",
      required: false,
      maxLength: 28,
    },
    {
      key: "hero.secondaryCtaHref",
      label: "Secondary CTA link (optional)",
      type: "text",
      placeholder: "https://codesandbox.io/...",
      required: false,
    },
    {
      key: "features.heading",
      label: "Features section heading (optional)",
      type: "text",
      placeholder: "Why teams pick it",
      required: false,
      maxLength: 60,
    },
    { key: "feature.1.title", label: "Feature 1 — title", type: "text", maxLength: 50 },
    { key: "feature.1.body", label: "Feature 1 — body", type: "textarea", maxLength: 200 },
    { key: "feature.2.title", label: "Feature 2 — title", type: "text", maxLength: 50 },
    { key: "feature.2.body", label: "Feature 2 — body", type: "textarea", maxLength: 200 },
    { key: "feature.3.title", label: "Feature 3 — title", type: "text", maxLength: 50 },
    { key: "feature.3.body", label: "Feature 3 — body", type: "textarea", maxLength: 200 },
  ],
};
